export type NeuropausaDificultad = 'Fácil' | 'Media' | 'Alta';

export interface NeuropausaExercise {
    id: number;
    nombre: string;
    categoria: string;
    tipo: string;
    funcionCognitiva: string;
    dificultad: NeuropausaDificultad;
    duracion: string;
    etiquetas: string[];
    instruccionesImg: string;
    problemaImg: string;
    solucionImg: string;
}

const S3 = 'https://material-adjunto.s3.us-east-2.amazonaws.com/neuropausas/';

/** Imagen de instrucciones — siempre la misma para todos los ejercicios */
export const NEUROPAUSAS_INSTRUCCIONES_IMG =
    S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+01+INSTRUCCIONES.png';

const I = NEUROPAUSAS_INSTRUCCIONES_IMG;

export const NEUROPAUSAS_EJERCICIOS: NeuropausaExercise[] = [
    {
        id: 1,
        nombre: 'Anagramas parciales',
        categoria: 'Lenguaje y Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria y lenguaje',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Lenguaje', 'Memoria', 'Concentración'],
        instruccionesImg: I,
        problemaImg:  S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ANAGRAMAS++PARCIALES+-+PROBLEMAS.png',
        solucionImg:  S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ANAGRAMAS++PARCIALES+-+SOLUCIONES.png',
    },
    {
        id: 2,
        nombre: 'Asociaciones',
        categoria: 'Razonamiento',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento asociativo',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Razonamiento', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ASOCIACIONES+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ASOCIACIONES+-+SOLUCIONES.png',
    },
    {
        id: 3,
        nombre: 'Bloque de pisos',
        categoria: 'Percepción Espacial',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento espacial',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Atención', 'Espacial', 'Razonamiento'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+BLOQUE+DE+PISOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+BLOQUE+DE+PISOS+-+SOLUCIONES.png',
    },
    {
        id: 4,
        nombre: 'Busca palabras',
        categoria: 'Atención Sostenida',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Atención y lenguaje',
        dificultad: 'Fácil',
        duracion: '2 min',
        etiquetas: ['Atención', 'Lenguaje', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+BUSCA+PALABRAS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+BUSCA+PALABRAS+-+SOLUCIONES.png',
    },
    {
        id: 5,
        nombre: 'Calcetines',
        categoria: 'Razonamiento Lógico',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento lógico',
        dificultad: 'Fácil',
        duracion: '2 min',
        etiquetas: ['Razonamiento', 'Atención', 'Lógica'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+CALCETINES+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+CALCETINES+-+SOLUCIONES.png',
    },
    {
        id: 6,
        nombre: 'Canicas',
        categoria: 'Cálculo y Lógica',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Cálculo y razonamiento',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Cálculo', 'Razonamiento', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+CANICAS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+CANICAS+-+SOLUCIONES.png',
    },
    {
        id: 7,
        nombre: 'Cena de verano',
        categoria: 'Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria episódica',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Atención', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+CENA+DE+VERANO+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+CENA+DE+VERANO+-+SOLUCIONES.png',
    },
    {
        id: 8,
        nombre: 'Cómo continúa',
        categoria: 'Razonamiento',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento por patrones',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Razonamiento', 'Atención', 'Patrones'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+COMO+CONTINUA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+COMO+CONTINUA+-+SOLUCIONES.png',
    },
    {
        id: 9,
        nombre: 'Completar mosaicos',
        categoria: 'Percepción Visual',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Percepción y atención visual',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Percepción', 'Atención', 'Visual'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+COMPLETAR+MOSAICOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+COMPLETAR+MOSAICOS+-+SOLUCIONES.png',
    },
    {
        id: 10,
        nombre: 'Dados asimétricos',
        categoria: 'Percepción Espacial',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Percepción espacial',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Espacial', 'Razonamiento', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+DADOS+ASIMETRICOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+DADOS+ASIMETRICOS+-+SOLUCIONES.png',
    },
    {
        id: 11,
        nombre: 'Diez manzanas',
        categoria: 'Cálculo y Lógica',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Cálculo y memoria',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Cálculo', 'Memoria', 'Razonamiento'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+DIEZ+MANZANAS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+DIEZ+MANZANAS+-+SOLUCIONES.png',
    },
    {
        id: 12,
        nombre: 'El ordenador',
        categoria: 'Razonamiento Lógico',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento lógico',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Lógica', 'Razonamiento', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+EL+ORDENADOR+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+EL+ORDENADOR+-+SOLUCIONES.png',
    },
    {
        id: 13,
        nombre: 'Estrella',
        categoria: 'Percepción Visual',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Percepción visual',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Visual', 'Atención', 'Percepción'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ESTRELLA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ESTRELLA+-+SOLUCIONES.png',
    },
    {
        id: 14,
        nombre: 'Falta uno',
        categoria: 'Atención Sostenida',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Atención y memoria',
        dificultad: 'Fácil',
        duracion: '2 min',
        etiquetas: ['Atención', 'Memoria', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+FALTA+UNO+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+FALTA+UNO+-+SOLUCIONES.png',
    },
    {
        id: 15,
        nombre: 'Fragmento',
        categoria: 'Percepción Visual',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Percepción visual',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Visual', 'Atención', 'Percepción'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+FRAGMENTO+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+FRAGMENTO+-+SOLUCIONES.png',
    },
    {
        id: 16,
        nombre: 'Fuga de vocales',
        categoria: 'Lenguaje y Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Lenguaje y memoria',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Lenguaje', 'Memoria', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+FUGA+DE+VOCALES+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+FUGA+DE+VOCALES+-+SOLUCIONES.png',
    },
    {
        id: 17,
        nombre: 'Intercambiados',
        categoria: 'Atención Sostenida',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Atención y percepción',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Atención', 'Percepción', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+INTERCAMBIADOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+INTERCAMBIADOS+-+SOLUCIONES.png',
    },
    {
        id: 18,
        nombre: 'La baraja',
        categoria: 'Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria y atención',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Atención', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LA+BARAJA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LA+BARAJA+-+SOLUCIONES.png',
    },
    {
        id: 19,
        nombre: 'La cuarta figura',
        categoria: 'Razonamiento',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento visual',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Razonamiento', 'Visual', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LA+CUARTA+FIGURA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LA+CUARTA+FIGURA+-+SOLUCIONES.png',
    },
    {
        id: 20,
        nombre: 'La pareja',
        categoria: 'Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria y asociación',
        dificultad: 'Fácil',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Asociación', 'Atención'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LA+PAREJA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LA+PAREJA+-+SOLUCIONES.png',
    },
    {
        id: 21,
        nombre: 'Laberinto de flechas',
        categoria: 'Atención Sostenida',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Atención y planificación',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Atención', 'Planificación', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LABERINTO+DE+FLECHAS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LABERINTO+DE+FLECHAS+-+SOLUCIONES.png',
    },
    {
        id: 22,
        nombre: 'Las diferencias',
        categoria: 'Atención Sostenida',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Atención y percepción',
        dificultad: 'Fácil',
        duracion: '2 min',
        etiquetas: ['Atención', 'Percepción', 'Visual'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LAS+DIFERENCIAS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+LAS+DIFERENCIAS+-+SOLUCIONES.png',
    },
    {
        id: 23,
        nombre: 'Media estrella',
        categoria: 'Percepción Visual',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Percepción visual',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Visual', 'Atención', 'Percepción'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MEDIA+ESTRELLA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MEDIA+ESTRELLA+-+SOLUCIONES.png',
    },
    {
        id: 24,
        nombre: 'Memoria laberíntica',
        categoria: 'Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria espacial',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Espacial', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MEMORIA+LABERINTICA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MEMORIA+LABERINTICA+-+SOLUCIONES.png',
    },
    {
        id: 25,
        nombre: 'Menos tres',
        categoria: 'Cálculo y Lógica',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Cálculo mental',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Cálculo', 'Atención', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MENOS+TRES+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MENOS+TRES+-+SOLUCIONES.png',
    },
    {
        id: 26,
        nombre: 'Monedas y pesos',
        categoria: 'Cálculo y Lógica',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Cálculo y razonamiento',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Cálculo', 'Razonamiento', 'Lógica'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MONEDAS+Y+PESOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+MONEDAS+Y+PESOS+-+SOLUCIONES.png',
    },
    {
        id: 27,
        nombre: 'Pirámide de letras',
        categoria: 'Lenguaje y Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Lenguaje y memoria',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Lenguaje', 'Memoria', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+PIRAMIDE+DE+LETRAS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+PIRAMIDE+DE+LETRAS+-+SOLUCIONES.png',
    },
    {
        id: 28,
        nombre: 'Por lógica',
        categoria: 'Razonamiento Lógico',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento lógico',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Lógica', 'Razonamiento', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+POR+LOGICA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+POR+LOGICA+-+SOLUCIONES.png',
    },
    {
        id: 29,
        nombre: 'Recordando símbolos',
        categoria: 'Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria visual',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Visual', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+RECORDANDO+SIMBOLOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+RECORDANDO+SIMBOLOS+-+SOLUCIONES.png',
    },
    {
        id: 30,
        nombre: 'Recordando un fragmento',
        categoria: 'Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Memoria visual',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Memoria', 'Atención', 'Visual'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+RECORDANDO+UN+FRAGMENTO+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+RECORDANDO+UN+FRAGMENTO+-+SOLUCIONES.png',
    },
    {
        id: 31,
        nombre: 'Reflejos',
        categoria: 'Velocidad de Procesamiento',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Velocidad de procesamiento',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Atención', 'Velocidad', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+REFLEJOS+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+REFLEJOS+-+SOLUCIONES.png',
    },
    {
        id: 32,
        nombre: 'Relación numérica',
        categoria: 'Cálculo y Lógica',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Cálculo y patrones',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Cálculo', 'Razonamiento', 'Patrones'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+RELACION+NUMERICA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+RELACION+NUMERICA+-+SOLUCIONES.png',
    },
    {
        id: 33,
        nombre: 'Rotación',
        categoria: 'Percepción Espacial',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Rotación mental',
        dificultad: 'Alta',
        duracion: '2 min',
        etiquetas: ['Espacial', 'Razonamiento', 'Visual'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ROTACION+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+ROTACION+-+SOLUCIONES.png',
    },
    {
        id: 34,
        nombre: 'Sigue el buen camino',
        categoria: 'Atención Sostenida',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Atención y planificación',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Atención', 'Planificación', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+SIGUE+EL+BUEN+CAMINO+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+SIGUE+EL+BUEN+CAMINO+-+SOLUCIONES.png',
    },
    {
        id: 35,
        nombre: 'Sílaba a sílaba',
        categoria: 'Lenguaje y Memoria',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Lenguaje',
        dificultad: 'Fácil',
        duracion: '2 min',
        etiquetas: ['Lenguaje', 'Memoria', 'Concentración'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+SILABA+A+SILABA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+SILABA+A+SILABA+-+SOLUCIONES.png',
    },
    {
        id: 36,
        nombre: 'Sobra una',
        categoria: 'Razonamiento',
        tipo: 'Neuropausa cognitiva',
        funcionCognitiva: 'Razonamiento y clasificación',
        dificultad: 'Media',
        duracion: '2 min',
        etiquetas: ['Razonamiento', 'Atención', 'Lógica'],
        instruccionesImg: I,
        problemaImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+SOBRA+UNA+-+PROBLEMAS.png',
        solucionImg: S3 + 'EMOCHECK+EJERCICIOS+NEUROPAUSAS+-+SOBRA+UNA+-+SOLUCIONES.png',
    },
    // Ejercicios 37–73 se agregarán aquí
];
